[package]
name = "swapmath"
version = "0.0.0"
upgrade_policy = "compatible"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
fixed_point64 = { local= "../fixedpoint64" }
manager = { local= "../manager" }

[addresses]
thalaswap_math = "0x29f060e36dfd2955f0aca99428c827fda17b19d017b199f24d7dcbc71ca164f5"
thalaswap_math_deployer = "0xeb2841b4b81d2d4daff72bdd340d9251307172f28dee492a3a78bb6b01e5b55f"